### ISSUE TITLE
Is Nova 4 support planned?

### ISSUE THREAD

**Issue by ziming** [dillingham/nova-attach-many#101]
Like to ask if there are plans to support Nova 4, if not then I will try to find some alternatives. Thanks!

**Comment by anditsung** [comment]
hi, i already create a PR for this.

**Comment by bashgeek** [comment]
Seems like this is kind of abandoned for now. If anybody is looking for a working Nova 4 version, here is our fork with this PR applied and used in production by us already:
https://github.com/blendbyte/nova-attach-many

**Comment by ziming** [comment]
@dillingham it would be great if you can merge the PR!

**Comment by dillingham** [comment]
Going to work on merging that pr soon

**Comment by alekmlynek** [comment]
Any luck on the PR?

**Comment by lptn** [comment]
any news, guys?

**Comment by abdulwahid** [comment]
@dillingham As you have already merged the PR https://github.com/dillingham/nova-attach-many/pull/100 into master. 
Are planning to create a new release for this?

**Comment by lptn** [comment]
Hey @dillingham
Can you please release a new major version of the package (with Nova v4 support)?

**Comment by roblegaspi** [comment]
+1

**Comment by NoahNxT** [comment]
@dillingham Please create a new release for it!

**Comment by ziming** [comment]
@dillingham you may have forgotten to tag a release after you merged this PR to support nova 4

**Comment by vesper8** [comment]
You must use `dev-master` for now.

Also, a duplicate `use` declaration causes fatal error. I created a PR https://github.com/dillingham/nova-attach-many/pull/106

**Comment by dillingham** [comment]
tagged a 2.0 release

**Comment by vesper8** [comment]
Awesome @dillingham !

I also just noticed that the Tailwind styles aren't all working in Nova 4, making your custom field look very.. unstyled.

I've created a PR which also explains why this happened: https://github.com/dillingham/nova-attach-many/pull/107

Cheers!
