### ISSUE TITLE
Usage in detail view

### ISSUE THREAD

**Issue by ben182** [dillingham/nova-attach-many#12]
Can this be also used in the detail view like a normal belongs to many relationship?

**Comment by dillingham** [comment]
@ben182 You can add a belongs to many relationship as you normally would

```php
AttachMany::make('Users'),
BelongsToMany::make('Permissions'),
```
These two don't interfere with one another because
- AttachMany is form only
- BelongsToMany is detail only

I didn't want to make this package responsible for functionality that nova already provides :)
