### ISSUE TITLE
Typo in release number ?

### ISSUE THREAD

**Issue by niladam** [dillingham/nova-attach-many#13]
Hi buddy. Again, **1.0.71** should be **1.0.8** according to SEMVER :)

**Comment by dillingham** [comment]
Is it though? I tried reading up on it and saw laravel using small increments and don’t want to switch to 1.1 sooner just because of a small tweak. I guess I should read up on it more :)

**Comment by niladam** [comment]
Here's the simplified version:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

So, **1** is **MAJOR**, **0** is **MINOR** and **7** (or 8) is the **PATCH**.

And yes, Laravel does use small increments, but in in the way you tried to do. If you wanted to increment the patch, you'd have used .8 as i said :)

If you do indeed come into a situation where you end up with a situation where you have (laravel's example): 5.7.22 (you'll see that the major version is 5, the minor is 7 and 22 represent the patches);

I hope you do eventually end up having versions like 1.5.22 -- this means you're working on it and it gives me great joy to see involved developers like you :)

Also, you can basically stick to 1.0 until you reach the maximum of 1.0.99 (but the patch number should be incremented if it's a patch only) :)

Keep up the good work! 👍

**Comment by dillingham** [comment]
Thank you so much for explaining that. I read and re-read the spec and it just for some reason didnt click for me and I was perceiving it as a decimal? 🤣 Im not sure honestly, .71 was lesser than .8 in my head.

But the info you provided makes alot of sense. DIdnt think that 0.0.9 turns into 0.0.10

Much appreciated!!

**Comment by dillingham** [comment]
Oh and I deleted the 1.0.71 tag and added a 1.0.8 release.. 
So any one who may have upgraded would downgrade?

**Comment by niladam** [comment]
You're welcome! It's in these times that us developers need to stick together. We're not the best in every area and we can always improve! I'm having situations like these were i get some 'aaaah' moments everyday! 

No worries. No-one was born knowing-it-all :) - it's a learning process - happy to have been of help -- at least in a form of gratitude for your work in this package.

Well, i honestly don't know. I've never met a situation where a release tag was 1.0.71. Personally, i'd make a minor increment and not just patch, as IMHO - the showpreview is a great addition and **improves** (see - it doesn't patch - like fix) the package.

But that's totally up to you :)
