### ISSUE TITLE
Help Text should work with HTML

### ISSUE THREAD

**Issue by BrandonSurowiec** [dillingham/nova-attach-many#14]
The help text should be displayed using the `<help-text>` component, which will allow HTML to be passed through.

```
<help-text class="help-text mt-2" v-if="showHelpText"> {{ field.helpText }} </help-text>
```

Right now it is using a `<span>` tag.

```
<span v-if="field.helpText" class="pr-2">{{ field.helpText }}</span>
```

To reproduce:

```
AttachMany::make('Permissions')->help('You shall <strong>not pass!</strong>'),
```

**Comment by niladam** [comment]
@BrandonSurowiec - you're right. I guess it was just a slip on @dillingham - i've created a pull request that should fix it. 

As soon as @dillingham gets a chance, he'll probably accept it and tag a new release supporting HTML :)

Thank you for raising this :)
