### ISSUE TITLE
Interesting behavior on model with many relationships + observer

### ISSUE THREAD

**Issue by ericdiviney** [dillingham/nova-attach-many#16]
Hey there, just wanted to comment on a recent issue I encountered in case it is useful for anyone.

First off, awesome work. This field is a gem.

To provide some background - I am currently building a new system in which this field was to help us manage a many-to-many polymorphic relationship. I am going to explain just for the sake of context. We have 3 models in our situation

Pages - eloquent model that can contain "attachable" resources (brands and models below) as well as reference ANOTHER page model (so, same class Page) as it's "parent"
Brands - an eloquent model that can be "attached" to a page
Models - an eloquent model that can be "attached" to a page

For some reason I was unable to find, upon "attaching" either brands or models to a Page, those attachables would also be applied to the Page's "children". So a Page model would have a `$page->children()` property to return a Collection of Pages that have THIS page set as their parent.

An interesting sidenote to be aware of, we have set up a "PageObserver" to monitor when a page is saved. The reason for this observer is when a "parent" page is updated, we loop through ALL the children (and grandchildren pages, if you're following) to "update" their unique query string (slug). In other words, we have a `query_url` string on our pages that represent it's FULL "route" from a dynamic perspective. Quick example:

We have a parent page and its child.

`/parent-slug/` << parent page query_url
`/parent-slug/child-slug/` << child page's query_url

Our observer was simply meant to do this:
`/parent-new-slug/`  << updated parent page query_url
`/parent-new-slug/child-slug/`  << updated child page's query_url

notice every child page's query needs to update so we know what page to fetch via the `query_url` column for `Page` model.

I just came here to say that by removing the static Eloquent `::saved()` method in `/src/AttachMany.php ` resolved this issue. Can't really say why - but figured it had something to do with the observer we had set up. The observer is a simple recursive method to "update" the column for each child of the page that was just "saved" in case the slug was changed. So what we did was change this:

```
if(is_subclass_of($model, 'Illuminate\Database\Eloquent\Model')) {
  model::saved(function($model) use($attribute, $request) {
    $model->$attribute()->sync(
      json_decode($request->$attribute, true)
    );
  });
  unset($request->$attribute);
}
```

To this:

```
if(is_subclass_of($model, 'Illuminate\Database\Eloquent\Model')) {
  
    $model->$attribute()->sync(
      json_decode($request->$attribute, true)
    );
 
  unset($request->$attribute);
}
```

I should also note that this issue only seemed to happen when moving "down" the page tree. Meaning if you changed the "attachables" for a page that has both a parent AND children, the new relation was applied to all children of that page but NOT the parent. This seemed to make sense and lead us to the conclusion it must have something to do with our observer. Since the page observer only traverses children to update their `query_url` and NOT the parents that seemed to be where the code-smell was. 

Happy to answer any questions you might have about this. Otherwise feel free to delete this issue and I won't bother again. We forked your repo and it has our little change and we haven't noticed any side effects or other bugs caused in the meantime. Thanks again!

**Comment by dillingham** [comment]
@ericdiviney thanks for the topic 
 and the use case with a complete set of details! I’ll think on this a bit and chime in soon.

**Comment by royduin** [comment]
@ericdiviney updating works without the observer but creating and entity fails because the model isn't created yet. That's why @dillingham is using the the `saved` observer.

I've some issues with it too; it's called multiple times because it seems like Nova is saving fields one by one so the `saved` event is triggered for every field and so is the `sync()` call.

And I've no idea how to determine the order of model events. When I create a model my own event is called earlier then the event which attaches the relations. So from my listener the relations aren't saved yet.

**Comment by dillingham** [comment]
@royduin / @ericdiviney added a synced method https://github.com/dillingham/nova-attach-many#being-notified-of-changes. I think that helps this problem so Im going to close. If not let me know :)
