### ISSUE TITLE
Show selected options in index view

### ISSUE THREAD

**Issue by kristianharmer** [dillingham/nova-attach-many#18]
Should selected options show in index view? 

Works fine in my form/s but doesn't show on the index or detail views.

**Comment by dillingham** [comment]
Checkout this comment
https://github.com/dillingham/nova-attach-many/issues/12#issuecomment-465759281

You can render a text input with like a count or something if you want, not really the goal of this package. 

Thanks for asking though

**Comment by kristianharmer** [comment]
Ah yes, I see, it's totally independent.  Thanks for the speedy reply and thanks for providing this.

**Comment by kristianharmer** [comment]
For anyone needing a solution, this worked for me:

`
Text::make('Categories', function () {

                    $categories = $this->categories()->get();

                    $displayCategories = '';
                    foreach($categories as $key => $category) {
                        if($key != 0) $displayCategories .= ', ';
                        $displayCategories .= $category->name;
                    }

                    return $displayCategories;
                }),
`
