### ISSUE TITLE
Double counting

### ISSUE THREAD

**Issue by ahmedkandel** [dillingham/nova-attach-many#2]
Hi Brian,

Small issue in counts, If some items are selected then you click select all the counter adds all count to existing count.
![1](https://user-images.githubusercontent.com/28398523/52723914-acb70000-2fae-11e9-944d-3d2e0e9e4cb2.png)
![2](https://user-images.githubusercontent.com/28398523/52723918-af195a00-2fae-11e9-91b8-958189726e6d.png)

**Comment by dillingham** [comment]
Ah thanks, I'll patch this today
