### ISSUE TITLE
Change the label of the relationship

### ISSUE THREAD

**Issue by phuclh** [dillingham/nova-attach-many#21]
Thank you for your field, it works great!!!.

However, I couldn't find a way to change the label like other fields. I already tried to pass the label as the 1st argument and the relationship as the 2nd argument, but it doesn't work.

`AttachMany::make('Categories: ', 'ProductCategories'),`

Thank you!!!

**Comment by loicm** [comment]
`AttachMany::make('Your label', 'attribute-used-as-value', YourRessource::class');`

So, for example, if you want to display the `name` attribute:

`AttachMany::make('Categories: ', 'name', ProductCategories::class');`

Hop that helps.

**Comment by dillingham** [comment]
@phuclh yeah what @loicm said. Thats how all fields usually work

**Comment by fede91it** [comment]
I got the error `Call to undefined method App\RelatedModel::uriKey()` why?

**Comment by lukdiekm** [comment]
@f-liva have you found a solution for that?

**Comment by lukdiekm** [comment]
@f-liva you have to user the nova-model-class as third param, not the laravel-model.
