### ISSUE TITLE
Category hierarchy

### ISSUE THREAD

**Issue by phuclh** [dillingham/nova-attach-many#22]
I have some product categories and they are hierarchy (parent and child). How can I display these categories in a tree, something like that:

```
A
-Child 1
B
-Child 1
-Child 2
```

Thank you for your help!!!

**Comment by phuclh** [comment]
Does anybody know how to solve that? Thank you!

**Comment by dillingham** [comment]
Maybe try multiple fields with scoped relationships 

Not something I plan to add sorry
