### ISSUE TITLE
relatableQuery

### ISSUE THREAD

**Issue by bsormagec** [dillingham/nova-attach-many#23]
Hello @dillingham, i checked it but can't found implementation of this type usage in your codebase is it easy to implement ? Or can i use it with this state ?

Thanks...

**Comment by dillingham** [comment]
@bsormagec yeah here is the section of the code that handles that
https://github.com/dillingham/nova-attach-many/blob/master/src/Http/Controllers/AttachController.php#L38-L42

you can do relatableQuery as well as authorization

**Comment by bsormagec** [comment]
My Resource name is Type and i am creating function as relatableTypes its working with BelongsToMany, but not working with this package can you help me whats wrong ?

**Comment by dillingham** [comment]
@bsormagec the answer is in my previous message.. it is calling relatableQuery on the resource

**Comment by bsormagec** [comment]
Thanks @dillingham thats my mistake i fixed it 👍
