### ISSUE TITLE
Method NovaAttachMany\AttachMany::buildAttachableQuery does not exist.

### ISSUE THREAD

**Issue by SmbatPoghosyan** [dillingham/nova-attach-many#28]
Hi! 
I want have AttachMany field and BelongsToMany field both in my resource.
But when I want attach it is throw this error 
Method NovaAttachMany\AttachMany::buildAttachableQuery does not exist.

**Comment by dillingham** [comment]
Not enough info

**Comment by SmbatPoghosyan** [comment]
Nova/Website.php
`AttachMany::make('Services'),
 BelongsToMany::make('Services'),`
App/Service.php
`public function websites()
    {
        return $this->belongsToMany('App\Website', 'website_services')->withTimestamps();
    }`
App/Website.php
`public function services()
    {
        return $this->belongsToMany('App\Service', 'website_services')->withTimestamps();
    }`

when I want attach service in website view it is throw error 

> Method NovaAttachMany\AttachMany::buildAttachableQuery does not exist.
