### ISSUE TITLE
Show results with title & subtitle

### ISSUE THREAD

**Issue by calvinps** [dillingham/nova-attach-many#34]
Would you consider adding a feature where you can optionally include the resource's subtitle in the list of results? I'm using this package to attach one or more locations when creating a new resource and showing the address as a subtitle below the location's name would be very helpful to my users.  Sometimes locations have the same name (e.g. there are multiple McDonald's in one city) so the subtitle is necessary to distinguish between multiple options.

**Comment by dillingham** [comment]
@calvinps great idea! Added via https://github.com/dillingham/nova-attach-many/commit/08e77090cb3932be196bf221410832740c2c9d64 and will be in next release
