### ISSUE TITLE
Creating/Updating crash "Cannot access protecred property" on some fields

### ISSUE THREAD

**Issue by NeoN0x** [dillingham/nova-attach-many#35]
Hi,

Thank you for this useful package !

I got an issue when Creating / Updating a ressource using a AttachMany field:

```
    "message": "Cannot access protected property Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest::$languages",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "...\\vendor\\dillingham\\nova-attach-many\\src\\AttachMany.php",
    "line": 52,
```

My ressource is pretty simple

```
// Nova resource
class Lawyer extends Resource
{
            // ...
            AttachMany::make('LegalFields')
                ->rules('min:1', 'max:5')
                ->showCounts()
                ->showPreview()
                ->hideToolbar()
                ->fullWidth(),
            AttachMany::make('Languages')
                ->rules('min:1', 'max:5')
                ->showCounts()
                ->showPreview()
                ->fullWidth()
            // ...
}

// Model
class Lawyer extends Model
{
    // ...
    public function languages()
    {
        return $this->belongsToMany('App\Language', 'lawyer_language');
    }

    public function legalFields()
    {
        return $this->belongsToMany('App\LegalField', 'lawyer_legal_field');
    }
}
```

LegalFields works as expected, but Languages make impossible to create or update the ressource and give me the "Cannot access protected property" error. I tested by removing "LegalFields" and Languages still crash.

Nova BelongsToMany field works fine, so the database structure and Model are corrects.

I removed the following line

https://github.com/dillingham/nova-attach-many/blob/66e0b01e1be3aecbbfc72e7df81b45bf7fb9674a/src/AttachMany.php#L52

And now it works as expected - I'm not sure what this line does and why it leaded to this error, only on this field (I'm quite new to Nova).

I can do additionnal tests or give more information if it can help you investigating and isolate the problem.

Thanks !

**Comment by marcuschristiansen** [comment]
@NeoN0x Have you had any further issues with that line removed? I'm running into the same issues

**Comment by martijn94** [comment]
Ran into the same issue. 

Seems it has something to do with `$languages` being a protected property on the class `Symfony\Component\HttpFoundation\Request` which in the end is being extended by `Laravel\Nova\Http\Requests\UpdateResourceRequest` where the `AttachMany` field is trying to unset the property.

I ended up fixing it by adding 

```
public function languagesForNova()
{
      return $this->languages();
}
```
to many model and changing the field to:
```
AttachMany::make('Languages', 'languagesForNova' )
```

Hope it helps.

**Comment by dillingham** [comment]
I think the answer to this is to use request->input() and request->delete() to avoid things like accessing $language property on the request class. The unset line is because you're saving a model and the json of all the relationships doesn't belong on the model even though its including in the request. I will tinker with this a bit. Thanks for the info everyone

**Comment by dillingham** [comment]
This should be solved in upcoming release via https://github.com/dillingham/nova-attach-many/commit/3dc0d8276268b6db9d225d85578c85b10645df7a
