### ISSUE TITLE
Error On Detail

### ISSUE THREAD

**Issue by bsormagec** [dillingham/nova-attach-many#39]
Hello @dillingham, 
When i use AttachMany and BelongsToMany for same Resource its crashing with,

`Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey()`

Because AttachMany working in Form but when i see this selected resources on detail, this error returning me. I checked it out and "**getForeignKey()**" method doesn't exists in "**Illuminate\Database\Eloquent\Relations\BelongsToMany**" when i add "**getForeignKey()**" method to "**Illuminate\Database\Eloquent\Relations\BelongsToMany**" everything everything works.
Can you check this state ?

**Comment by dillingham** [comment]
You don’t use it on detail
You use a normal BelongsToMany
At least that’s the case for now
Maybe I could do some work around to do that by default

**Comment by bsormagec** [comment]
I want to tell i am using it for Form but i need to show chosen selects in detail and when i use for it BelongsToMany, it returns error. I am asking how to fix this ? @dillingham

**Comment by dillingham** [comment]
Show me your fields

**Comment by bsormagec** [comment]
```
Text::make(__('Department Name'), 'name'),
            BelongsTo::make(__('Corporate'), 'corporate', Corporate::class),
            BelongsTo::make(__('Parent Department'), 'parent', __CLASS__)->nullable()->hideFromIndex(),
            Text::make(__('Department Code'), 'department_code')->nullable(),
            BelongsTo::make(__('Location'), 'location', Location::class),
            BelongsTo::make(__('User'), 'user', User::class)->hideWhenCreating()->hideFromIndex()->hideFromDetail()->hideWhenUpdating(),
            AttachMany::make(__('Owners'), 'owners', User::class),
            AttachMany::make(__('Users'), 'users', User::class),
            Notes::make(__('Notes'), 'notes'),

            //Has Many
            new Tabs(__('Relations'), [
                BelongsToMany::make(__('Users'), 'users', User::class),
                BelongsToMany::make(__('Owners'), 'owners', User::class),
            ]),

            new Tabs(__('Childs'), [
                HasMany::make(__('Sub Department'), 'childrens', __CLASS__),
            ]),
```

These are fields.

**Comment by ahmedkandel** [comment]
@bsormagec I don't know if this could help you or not, try to set the BelongsToMany before AttachMany
like:
```
BelongsToMany::make(__('Owners'), 'owners', User::class),
AttachMany::make(__('Owners'), 'owners', User::class),
```
Not:
```
AttachMany::make(__('Owners'), 'owners', User::class),
BelongsToMany::make(__('Owners'), 'owners', User::class),
```

This helped me to fix some undefined label issues and may help you too. I will try to check the reason behind this as I think some Nova updates introduced changes that lead to such behavior.

**Comment by cord** [comment]
> This helped me to fix some undefined label issues and may help you too.

can confirm this issue and the solution to re-order the fields - AttachMany seems to initialise the field object also used by BelongsToMany

**Comment by steks89** [comment]
If you remove this line 
$this->resourceName = $resource::uriKey();
from AttachMany class

Everything seems to work fine. I could use BelongsToMany with AttachMany

**Comment by dillingham** [comment]
This doesn't seem to be an issue in recent version of Nova.

Ill re-open if anyone is experiencing this still
