### ISSUE TITLE
Route cache issue

### ISSUE THREAD

**Issue by ahmedkandel** [dillingham/nova-attach-many#4]
Hi Brian,

when executing `php artisan route:cache` an error appears regarding the serialization as following:

> LogicException  : Unable to prepare route [nova-vendor/nova-attach-many/test] for serialization. Uses Closure. at /home/forge/domain.tld/vendor/laravel/framework/src/Illuminate/Routing/Route.php:917

Thanks.

**Comment by oxan** [comment]
This can easily be resolved by dropping the `test` route from `routes/api.php`.

**Comment by dillingham** [comment]
@ahmedkandel @oxan thanks, removed in 1.0.4
