### ISSUE TITLE
resourceId is empty on 2.0.8+

### ISSUE THREAD

**Issue by gaabora** [dillingham/nova-attach-many#40]
Hello. After nova 2.0.8 i got initially unselected checkboxes while editing.
I found that in `setInitialValue()` method `this.resourceId` remains undefined even when editing.

**Comment by gaabora** [comment]
nah, only 2.0.8, fixed on 2.0.9 (forgot to `php artisan nova:publish`)

**Comment by 4unkur** [comment]
@gaabora Thanks for posting the solution )
