### ISSUE TITLE
Unable to use canSee method

### ISSUE THREAD

**Issue by depsimon** [dillingham/nova-attach-many#41]
I'd like to hide the AttachMany fields on some condition. For this I use the `canSee` method.

Turns out because the `authorize` method is build so that if `canSee` returns false, it still shows the field.

In order to fix this I placed this condition at the top of the `authorize` method of the `AttachMany` class.

```php
public function authorize(Request $request)
{
    if (property_exists($this, 'seeCallback') && ! is_null($this->seeCallback)) {
        return $this->authorizedToSee($request);
    }

    ...
}
```

I am not sure that it's really a good fix.

Now it works when I use

```php
AttachMany::make(__('Team(s)'), 'teams', Team::class)
    ->canSee(function ($request) {
        return $this->audience === 'teams';
    }),
```

**Comment by dillingham** [comment]
@depsimon thanks! :)
