### ISSUE TITLE
It would be cool if this package support for pivot fields 

### ISSUE THREAD

**Issue by shingsoso** [dillingham/nova-attach-many#45]
It would be cool if this package can support for pivot fields like the original nova BelongsToMany Field

**Comment by tushar-kharmate** [comment]
Any Updates on this: It would be cool if this package support for pivot fields #45

**Comment by didix16** [comment]
Any updates of this improvement?

**Comment by dillingham** [comment]
I don't have plans for this sorry. Use belongs to many if you want that field.
