### ISSUE TITLE
Default Selections

### ISSUE THREAD

**Issue by skeetyeet** [dillingham/nova-attach-many#46]
Hi,

This package is a real awesome. Sorry for bad english but is there a way to set some default selections?

**Comment by skeetyeet** [comment]
![image](https://user-images.githubusercontent.com/41348548/65374687-ff3c6580-dccf-11e9-8687-4556960d4caf.png)


Hi, I found that in AttachController class in edit() 'id' was being searched for. I had a custom primary key that was not 'id'. I implemented the use of modelKeys() and it worked like a charm. 

Hope this helps anyone else. Thanks.

**Comment by buzkall** [comment]
Another option when using custom id columns is to define a getIdAttribute function in your model file and just return the custom id like this:

```
public function getIdAttribute() {
  return $this->YOUR_ID_NAME;
}
```

Also you can make all your models extend a custom BaseModel file (which will extend Model) and set there the function:

```
class BaseModel extends Model

    public function getIdAttribute()
    {
        return $this->{$this->getKeyName()};
    }
}
```
