### ISSUE TITLE
Unable to set inverse side of relationship in observer

### ISSUE THREAD

**Issue by mdavis1982** [dillingham/nova-attach-many#48]
## Problem
When using the AttachMany field, and having an observer set up, the attached models are not available in the observer.

## Setup
I have a model: `Author`.

My `Author` model has a `relatedAuthors` relationship:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Author extends Model
{
    public function relatedAuthors(): BelongsToMany
    {
        return $this->belongsToMany(self::class, 'related_authors', 'author_id', 'related_author_id');
    }
}
```

In my Nova resource, I have the `AttachMany` field set up as follows:

```php
AttachMany::make('Related Authors', 'relatedAuthors', self::class)
    ->showCounts()
    ->showPreview()
    ->help('The author(s) that are related to this one'),
```

When I use the form and select some related authors, everything works as it should. In my app, however, I need to also set the created / updated author as a related author of all the authors selected in the `AttachMany` field. I attempted to do this via an observer. It seems, however, that at the point the observer fires, the related authors haven't been set:

```php
class AuthorObserver
{
    public function saved(Author $author): void
    {
        // This returns 0 when saving for the first time, regardless of
        // how many related authors are selected in the create form.
        // ---
        // On subsequent saves, it returns the previous amount of related
        // authors and doesn't reflect the changes when selecting / deselecting
        // related authors in the update form
        $count = $artist->relatedAuthors->count();
    }
}
```

It doesn't matter if I do `$author->fresh()` in the observer, the result is still the same. This means that it's not possible for me to reliably do what I need.

It almost seems as though the observer is firing before any relations have been saved, which could very well be the case.

I think it's because of this line: https://github.com/dillingham/nova-attach-many/blob/master/src/AttachMany.php#L46

It seems as though the saved event is being fired, and then the sync is happening.

Is there a way around this?

Thanks 😄

**Comment by mdavis1982** [comment]
Does anyone have any suggestions for this? 😄

**Comment by mdavis1982** [comment]
I've opened #50 which would allow this functionality easily 😄

**Comment by dillingham** [comment]
@mdavis1982 thank you so much for this. Im truly sorry it took me so long to get around to reviewing.

I was unable to merge the PR cause it was closed. I added it with a tweak, instead of on model.. on the resource.

I will add a thanks to the release notes and link the original PR. Thanks again!

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-attach-many/commit/3fc36244ea6befc6a6c5fddf9c1e086e21e5384b
