### ISSUE TITLE
filters on option

### ISSUE THREAD

**Issue by Ange7** [dillingham/nova-attach-many#5]
hey,

is it possible to filter on available option ? 

```
AttachMany::make( 'customer')->filters(function($customer){
    if($customer->is_disabled) return false;
});
```

For example  ?

**Comment by dillingham** [comment]
@Ange7 yes but with the [relatableQuery](https://nova.laravel.com/docs/1.0/resources/authorization.html#relatable-filtering)

AttachMany automatically calls that method for that purpose.
