### ISSUE TITLE
Label undefined on BelongsToMany

### ISSUE THREAD

**Issue by OliverZiegler** [dillingham/nova-attach-many#52]
When using this field along with the Nova default BelongsToMany, the order applied is critical.

Inserting AttachMany in the fields array before BelongsToMany, on the attach view of BelongsToMany the labels will show `undefined` instead of defined Labels.

It seems like the attach view will not use BelongsToMany but the AttachMany vue component?

**Comment by bsormagec** [comment]
same as me try to put BelongsToMany relation Before AttachMany

**Comment by didix16** [comment]
Thanks @bsormagec. I spent 2h trying to make it work...

**Comment by bsormagec** [comment]
👍🏻 @didix16

**Comment by dillingham** [comment]
This doesn't seem to be an issue in recent version of Nova.

Ill re-open if anyone is experiencing this still
