### ISSUE TITLE
Can not filter returned data 

### ISSUE THREAD

**Issue by odaiderawi** [dillingham/nova-attach-many#54]
How to filter the returned data 
i already using RelatableQurey in resource but with no any changes on data

**Comment by dillingham** [comment]
It calls the resource class relatableQuery here
https://github.com/dillingham/nova-attach-many/blob/master/src/Http/Controllers/AttachController.php#L36-L39

Maybe double check if its on the right resource or something

**Comment by odaiderawi** [comment]
I`m using it like this at my item resource 

![image](https://user-images.githubusercontent.com/36736057/72801787-f4c8b300-3c52-11ea-8df8-4684ec3f4180.png)


when add new item i want to attach it to many stores but not any branches
i need to filter the AttachMany Stores
but whatever i do the returned data still the same without any filtration

**Comment by dillingham** [comment]
it only checks relatableQuery

**Comment by odaiderawi** [comment]
its give the same results !

**Comment by dillingham** [comment]
Ok!
