### ISSUE TITLE
Bug when using 2 AttachMany fields 

### ISSUE THREAD

**Issue by halberio** [dillingham/nova-attach-many#55]
When i use 2 AttachMany fields in the resource class it gives for both same values
Example: 
`AttachMany::make('Roles Utilisateur', 'morphToMany', CustomRole::class),
       AttachMany::make('Permissions Utilisateur', 'morphToMany', CustomPermission::class),`

I get only the values of roles in select,  ( It always takes the values of the first one )

**Comment by andypa** [comment]
@halberio I experienced the same problem but only because I copy&pasted the second Nova resource. Check in your CustomRole::class and CustomPermission::class if the property

```
public static $model = "...";
```

corresponds to the correct model.
