### ISSUE TITLE
Small change to the readme

### ISSUE THREAD

**Issue by LaurensDorival** [dillingham/nova-attach-many#57]
Hi Brian,

First of all, thanks for releasing this package! 

My issue: I have a Laravel model with a many-to-many relationship to itself trough a pivot table. 
It took me some time figuring out how to make this work, because it wasn't apparent to me how to do this at first. 

The solution was to supply AttachMany::make with two additional arguments: the relationships name and the class name of that same Resource.

So something like this:
`
AttachMany::make('MyModel', 'my_models_relationship_to_its_children', 'app\Nova\MyModel')
`

Could you please add this to your readme to save the next sucker some time ;-)

Thanks!

**Comment by dillingham** [comment]
@LaurensDorival great suggestion thank you! Updated the readme
