### ISSUE TITLE
[FEATURE REQUEST] Add possibility to refresh attachable resources

### ISSUE THREAD

**Issue by pragmaticus** [dillingham/nova-attach-many#63]
**Current situation**

1. Create a new resource
2. Fill out all fields
3. Trying to attach a resource, but realizing i didn't create the foreign resource beforehand
4. Save the new resource (from point 1.)
5. Create the new foreign resource
6. Edit the new resource (from point 1.) and attach the foreign resource (from point 5.)
7. Save the resource (from point 1.)

**Suggestion**
1. Create a new resource
2. Fill out all fields
3. Trying to attach a resource, but realizing i didn't create the foreign resource beforehand
4. Create the foreign resource in a different tab, save it and close the tab.
5. **NEW FEATURE** Hit refresh on the relationship field of the new resource (from point 1.)
6. Attach the new foreign resource (from point 4.)
7. Save the new resource (from point 1.)

What do you think?

(Thanks for your work, it really enhances the default workflow of nova and many to many relations)

**Comment by dillingham** [comment]
@pragmaticus I think this could be useful! Thanks for the detailed walk through.

Im going to hold off for now but I might circle back and add it so I don't want to close it :)
