### ISSUE TITLE
Overriding indexQuery in Resource doesn't take an effect

### ISSUE THREAD

**Issue by aghayeff** [dillingham/nova-attach-many#65]
Hi, thanks for the package!

In Resource, if I override an indexQuery like

    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('active', true);
    }

Using BelongsTo field it takes an effect, but doesn't work if use AttachMany instead of BelongsTo.

**Comment by rashad-bestcomp** [comment]
You mean instead of indexQuery using RelatedQuery? I tested it, but no any result
