### ISSUE TITLE
Feature Request: Add support for depend on another field 

### ISSUE THREAD

**Issue by Peterragheb** [dillingham/nova-attach-many#66]
Please add support for depending on another field to filter the options

**Comment by dillingham** [comment]
Hey @Peterragheb 👋

Can you provide more context? Maybe a code example / scenario?

Initially seems very specific and may not be something I'd want to support.
But wanted to fully consider the use case before discarding the idea 👍 

---
~  Brian Dillingham ([@im_brian_d](https://twitter.com/im_brian_d))

**Comment by Peterragheb** [comment]
Okay here is an example:
If we have Project, Platform and Request resources
Request belongsto Project
Project BelongstoMany Platform
Request BelongstoMany Platform

In the nova resource of request we have :
Belongsto field for project
And attachMany field for Platform 
Here we only want to show the platforms available through the selected project

In general the feature that I'm requesting is to make the field dependent on the value of another field
