### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by ahmedkandel** [dillingham/nova-attach-many#7]
Hi Brian,

As enhancement will be better to have loading indicator while the list is being grabbed from the server. e.g. I have countries list of 245 items that takes 2s to populate it make use confused why the attach many list is empty.

It is related to the pagination option you are working on but will be better user experience to have an indicator on low-performance systems.

Thanks.

**Comment by dillingham** [comment]
Thanks for the suggestion. 
I will add this enhancement first.

**Comment by ahmedkandel** [comment]
Hi Brian, If you like I can make a PR for this.

**Comment by ahmedkandel** [comment]
PR is ready when you want.

**Comment by dillingham** [comment]
@ahmedkandel thanks, I went ahead and added a basic loading atate

**Comment by ahmedkandel** [comment]
@dillingham 👍 Thanks for the swift reply. I had this [commit ](https://github.com/ahmedkandel/nova-attach-many/commit/20c5f7b84cd2d831b4ee5375e59c6c8f1bd85df5) using nova loader component to cope more with the nova style if you like to take it or use in somehow.

**Comment by dillingham** [comment]
@ahmedkandel ah didn't think of that, added and released :)
