### ISSUE TITLE
tag 1.0.12

### ISSUE THREAD

**Issue by alberto-bottarini** [dillingham/nova-attach-many#70]
I noticed you merged some useful PRs into master branch.

What about forge a new tag?

Thanks a lot for your work

**Comment by dillingham** [comment]
Hey @alberto-bottarini,

Im going to do some more testing and see if I can address any other quick fixes before releasing.

Still have to figure out if this release would break anything haha

**Comment by alberto-bottarini** [comment]
Great!
I can't wait to update my codebase 🍰

**Comment by dillingham** [comment]
@alberto-bottarini I tagged https://github.com/dillingham/nova-attach-many/releases/tag/1.1.0

I didn't find any issues / seems to work smoothly. If you find anything let me know! :)

Thanks for your help!
