### ISSUE TITLE
HasMany support discussion

### ISSUE THREAD

**Issue by dillingham** [dillingham/nova-attach-many#74]
Wanted to open this up for discussion as I have been trying to wrap my head around the sought after topic. 

Some folks seem to want to update many models to be owned by a model via the it's create / edit view.

A User could be the Parent `parent_id` of many Users.

A User could be the author `author_id` of many Posts

So basically [at this point](https://github.com/dillingham/nova-attach-many/blob/master/src/AttachMany.php#L65) we would have to determine if the relationship needs a sync or the following.

---

Here is my initial thoughts in terms of implementation:

```php
DB::table('users')
    ->where('parent_id', $resource->id)
    ->whereNotIn('id', $idArray)
    ->update([ 'parent_id' => null ]);
```
^ Remove any that were previously selected but were unchecked.

```php
DB::table('users')
    ->whereIn('id', $idArray)
    ->update([ 'parent_id' => $resource->id ]);
```
^ Add any that were checked

Additionally, would need the original array of attached IDs for [$changes](https://github.com/dillingham/nova-attach-many#being-notified-of-changes)

---

Because of policies and other stuff, Im wondering if this would be better as its own package though.

Any thoughts or concerns are welcome. Not sure I will be adding this or not.

# Related
https://github.com/laravel/nova-issues/issues/520
https://github.com/dillingham/nova-attach-many/pull/64
https://github.com/dillingham/nova-attach-many/issues/56
https://github.com/laravel/nova-issues/issues/2815

**Comment by 0x15f** [comment]
In my fork, I am working on implementing this, the only issue I am running into is that I cannot determine if the foreign key on the relationship is `nullable`. If the column is `nullable` then it can be updated to `null` when "deattaching" a HasMany relationship, if it is not `nullable` then the resource needs to be deleted. Currently, the only way I see doing that is attempting to update it to null and catching the error. I think this enhancement is for very specific use cases and each of those cases may require a different implementation like ours does.

**Comment by rasmustaarnby** [comment]
Hi @dillingham, 

This is package is so close to what I have been searching for.

Out of curiosity, what the reasoning behind closing this issues? It seems it would help to solve an issue that many face.

**Comment by dillingham** [comment]
@rasmustaarnby honestly I haven't used Nova in over a year.

Feel free to fork it and add the missing parts :)

**Comment by rasmustaarnby** [comment]
Ahh, fair enough. Thanks for sharing. 

Already found a way of extending the field so it works, without touching the core code of this package, so I'm happy.

**Comment by huantransuper** [comment]
@rasmustaarnby Can you please share the solution ?

**Comment by rasmustaarnby** [comment]
@huantransuper Sure, we are not using it anymore as we have found/redesigned that part of the DB structure but looking back in git, this I think the following is what we had.

This was in a resource named `Partner`, so the relation was Partner->hasMany->Locations

$attribute matches the table name, in this case `locations`

```php
AttachMany::make('Locations')
    ->showSubtitle()
    ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
        if (!is_subclass_of($model, 'Illuminate\Database\Eloquent\Model')) {
            return;
        }
        $model::saved(function ($model) use ($attribute, $request) {
            // fetch the submitted values
            $values = json_decode($request->input($attribute), true);

            // if $values is null make it an empty array instead
            if (is_null($values)) {
                $values = [];
            }

            // remove `null` values that may be submitted
            $filteredValues = array_filter($values);

            // Remove
            DB::table($attribute)
                ->where('partner_id', $model->id)
                ->update(['partner_id' => null]);

            // Add
            DB::table($attribute)
                ->whereIn('id', $filteredValues)
                ->update(['partner_id' => $model->id]);
        });
    }),
```
