### ISSUE TITLE
array_filter() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by slonomag** [dillingham/nova-attach-many#75]
Hi!

There are an issue in the latest release 1.1.0. Previously all worked fine.

"message": "array_filter() expects parameter 1 to be array, null given",
"exception": "ErrorException",
"file": "D:\\OpenServer\\domains\\...\\vendor\\dillingham\\nova-attach-many\\src\\AttachMany.php",
"line": 62,

My php version is 7.4. The issue comes when nothing selected. When I make a selection all works fine.

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-attach-many/releases/tag/1.1.1
