### ISSUE TITLE
array_filter() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by RazmikSaghoyan** [dillingham/nova-attach-many#79]
https://github.com/dillingham/nova-attach-many/blob/7bd425332ddf1efbe31792701274913a2f971c5f/src/AttachMany.php#L62

@drsdre  @bsormagec  @alberto-bottarini @mbardelmeijer @bdelamatre 

Please, fix this issue. $value can't be null.

FIx:
// remove `null` values that may be submitted
$filtered_values = array_filter($values ?? []);

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-attach-many/releases/tag/1.1.1
