### ISSUE TITLE
Passing the attached count() to be accessed in an Observer?

### ISSUE THREAD

**Issue by latwelve** [dillingham/nova-attach-many#84]
Hi sorry if this is not specifically related to your package, but do you know how I can get the true count() of the number of "attached" relations? 

I see in the observer its easy to get the previously saved value but I need to calculate a field (total) based on the new number and I have to do this before saved()

Is this a nova quirk or field quirk or a laravel thing?

Thank you

**Comment by dillingham** [comment]
@latwelve sorry but this is not specifically related to my package
