### ISSUE TITLE
Not working inside Dependancy Container

### ISSUE THREAD

**Issue by swapnilnandgave** [dillingham/nova-attach-many#87]
I have requirement to either select items from Attach Many or add through JSON KeyValue field. I have boolean flag whether to add manually or select from list. When I used inside dependancy container then getting 

**Trying to get property resourceClass of non object** 

I have used inside both packages but not working
https://packagist.org/packages/epartment/nova-dependency-container
https://novapackages.com/packages/digital-creative/conditional-container

**Comment by dillingham** [comment]
Sorry I haven't used that package and don't want to add a bunch of if statements in this package for other packages.

Here is a PR you can fork and add if its a requirement for your project

https://github.com/dillingham/nova-attach-many/pull/25
