### ISSUE TITLE
Using this field in an action

### ISSUE THREAD

**Issue by albalooshi** [dillingham/nova-attach-many#9]
Cool package, I am trying to use it in an action,  however Its trying to access the resource in the App/Nova/Actions/{ModelName} which is resulting in an error.

Is there a way to fix this?

**Comment by dillingham** [comment]
Haven’t tried it on actions yet. Will soon. 

But try 

AttachMany::make(‘Users’, ‘users’, \App\Nova\User::class)

**Comment by albalooshi** [comment]
@dillingham 
Already tired it before, got this error.
![image](https://user-images.githubusercontent.com/13213888/52970645-98676e80-33c5-11e9-9c92-0bfd75e928db.png)

**Comment by dillingham** [comment]
What exactly are you trying to do? 

Because this field is designed to allow attaching pivot rows
Are you trying to select multiple rows and attach multiple models?
Or use this as like a "Select Many" in an action and not attach?

**Comment by albalooshi** [comment]
I was trying to attach the selected options to many models at the same time. But I decided its not needed any more. 

Thank you for the awesome package.
